[theme]
primaryColor="#96CCFF"
backgroundColor="#D9E8FF"
secondaryBackgroundColor="#FFCFDE"
textColor="#2E2E2E"
font = "Verdana"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
